# User Persistence Dependencies for Nullary Apps
# 
# Add these dependencies to your Tauri app's Cargo.toml file
# to enable the shared user persistence system.

[dependencies]
# Core Tauri dependencies (should already exist)
tauri = { version = "2.6.2", features = [] }
tauri-plugin-shell = "2.0"
tauri-plugin-fs = "2.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# For HTTP requests (should already exist)
reqwest = { version = "0.12.4", default-features = false, features = ["blocking", "json", "multipart", "rustls-tls"] }

# For sessionless key generation and crypto
sessionless = "0.1.1"
hex = "0.4"

# For secure key storage (when implemented)
# Uncomment when ready to implement Stronghold:
# tauri-plugin-stronghold = "2.0"

# Planet Nine service client crates (should already exist)
# These paths should be adjusted based on your app's location relative to the services
bdo-rs = { path = "../../../../bdo/src/client/rust/bdo-rs" }
sanora-rs = { path = "../../../../sanora/src/client/rust/sanora-rs" }
dolores-rs = { path = "../../../../dolores/src/client/rust/dolores-rs" }
fount-rs = { path = "../../../../fount/src/client/rust/fount-rs" }
addie-rs = { path = "../../../../addie/src/client/rust/addie-rs" }

# Optional: Additional utilities
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.21"
tokio = { version = "1.0", features = ["full"] }

# Example complete Cargo.toml for a Nullary app:
# 
# [package]
# name = "your-app"
# version = "0.1.0"
# description = "Your Nullary app description"
# authors = ["Your Name"]
# license = "MIT"
# edition = "2021"
# 
# [lib]
# name = "your_app"
# crate-type = ["staticlib", "cdylib", "rlib"]
# 
# [build-dependencies]
# tauri-build = { version = "2", features = [] }
# 
# [dependencies]
# # Copy all dependencies from above
# tauri = { version = "2.6.2", features = [] }
# # ... etc
# 
# [features]
# default = ["custom-protocol"]
# custom-protocol = ["tauri/custom-protocol"]